---
# This playbook is to trigger compose files

- name: Project to automate use-cases from template
  hosts: dev
  gather_facts: no
  vars_files:
    - group_vars/common/vars_common_all.yml
    - group_vars/usecases/vars_usecases.yml
  roles:
    - mkouhei.include_csv
    - common
    - usecases/build_playbooks
    
