---

- name: "UC: Various Build directories"
  file:
    path: "{{build_base}}/{{buildDir}}/{{item[1]}}"
    state: "{{item[0]}}"
    mode: "u=rwx,g=rwx,o=rwx"
    recurse: yes
  with_nested:
    - directory
    - [ 'playbooks']

# Populate usecase_configs field values
# data is stored in a variable whose name is the CSV file name without the extension
- include_csv:
    src: "{{uc_L3_csv}}"
    outname: "uc_L3_list"
