---
# Default base settings
ls_version: "7.6.2"

# OS user
ls_user: elasticsearch
ls_group: elasticsearch

# ls_PATH_CONF=/path/to/my/config
#Need to provide default directories
ls_install_dir: "/opt/logstash"
ls_conf_dir: "{{ ls_install_dir }}/custom"



#These are used for internal operations performed by ansible.
#They do not affect the current configuration
ls_api_scheme: "http"
ls_api_host: "localhost"
ls_api_port: 9200
ls_api_uri: "{{ ls_api_scheme }}://{{ ls_api_host }}:{{ ls_api_port }}"
# Default base settings


# JVM custom parameters
ls_java_home: ''
ls_jvm_custom_parameters: ''
ls_heap_size: "1g"
