---

# -------------------------------------------------------------- #
# Common variables for DEV
# -------------------------------------------------------------- #
src_base: ".."
project: "uc_automate"
build_base: "/tmp/{{project}}"
buildDir: "buildDir"
configs: "config_management"
usecase_configs: "usecase_configs"
# -------------------------------------------------------------- #
# Download files Details
# -------------------------------------------------------------- #
# -------------------------------------------------------------- #

# -------------------------------------------------------------- #
# Individual Configs Directory
# -------------------------------------------------------------- #
# -------------------------------------------------------------- #


# -------------------------------------------------------------- #
